# Generated by Django 4.2.5 on 2023-10-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_questions', models.PositiveIntegerField()),
                ('marks_per_question', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
            ],
        ),
    ]
